name: time-orchestrator-infra

services:
  lgtm:
    image: grafana/otel-lgtm:0.28.0
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
      - "3200:3200"
      - "4040:4040"
      - "9090:9090"
      - "4317:4317"
      - "4318:4318"
    networks:
      - time-orchestrator

  auth:
    image: quay.io/keycloak/keycloak:26.6
    environment:
      KC_HOSTNAME: http://localhost:8443
      KC_HTTP_PORT: 8443
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      POSTMAN_CLIENT_SECRET: postman_secret
    command: "start-dev --import-realm"
    ports:
      - "8443:8443"
    volumes:
      - auth-data:/opt/keycloak/data
      - ./local-provision/keycloak:/opt/keycloak/data/import:ro
    healthcheck:
      test: "{ printf 'HEAD /health/ready HTTP/1.0\r\n\r\n' >&0; grep 'HTTP/1.0 200'; } 0<>/dev/tcp/localhost/9000"
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 5s
    restart: always
    networks:
      - time-orchestrator

  config:
    build:
      dockerfile: config-server/Dockerfile
      context: .
    environment:
      LOGGING_EXPORT_ENDPOINT: http://lgtm:4318/v1/logs
      TRACING_EXPORT_ENDPOINT: http://lgtm:4318/v1/traces
      METRICS_EXPORT_ENDPOINT: http://lgtm:4318/v1/metrics
    develop:
      watch:
        - action: rebuild
          path: config-server
          ignore:
            - target
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 3s
    restart: always
    networks:
      - time-orchestrator

networks:
  time-orchestrator:
    driver: bridge

volumes:
  auth-data: