name: time-orchestrator
include:
  - compose.infra.yaml

services:
  pgadmin:
    image: dpage/pgadmin4:9.16
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@time-orchestrator.com
      PGADMIN_DEFAULT_PASSWORD: admin
    profiles:
      - tools
    ports:
      - "5430:80"
    volumes:
      - ./local-provision/pgadmin/servers.json:/pgadmin4/servers.json:ro
    networks:
      - time-orchestrator

  prometheus:
    image: prom/prometheus:v3.13.0
    ports:
      - "9090:9090"
    depends_on:
      user:
        condition: service_healthy
    volumes:
      - ./local-provision/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - time-orchestrator

  grafana:
    image: grafana/grafana:9.1.7
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GH_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    depends_on:
      prometheus:
        condition: service_started
    volumes:
      - ./local-provision/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    networks:
      - time-orchestrator

  user-db:
    image: postgres:18.4-alpine
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "users"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 3s
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - time-orchestrator-user-service-postgres-data:/var/lib/postgresql
    networks:
      - time-orchestrator

  user:
    build:
      dockerfile: user-service/Dockerfile
      context: .
    environment:
      CONFIG_SERVER_URL: http://config:8888
      DB_URL: user-db:5432/users
      DB_USERNAME: admin
      DB_PASSWORD: admin
      AUTH_PUBLIC_URL: http://localhost:8443/realms/time-orchestrator
      AUTH_JWK_SET_URL: http://auth:8443/realms/time-orchestrator/protocol/openid-connect/certs
      SPRING_PROFILES_ACTIVE: compose
    develop:
      watch:
        - action: rebuild
          path: user-service
          ignore:
            - target
            - src/main/resources/db
    ports:
      - "8080:8080"
    depends_on:
      auth:
        condition: service_healthy
        restart: true
        required: true
      config:
        condition: service_healthy
        restart: true
        required: true
      user-db:
        condition: service_healthy
        restart: true
        required: true
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 3s
    restart: always
    networks:
      - time-orchestrator

volumes:
  time-orchestrator-user-service-postgres-data:
