server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/darwin-s/time-orchestrator-config
          default-label: master
        native:
          search-locations: file:///${CONFIG_DIR}

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
  observations:
    annotations:
      enabled: true
  opentelemetry:
    logging:
      export:
        otlp:
          endpoint: ${LOGGING_EXPORT_ENDPOINT:http://localhost:4318/v1/logs}
    tracing:
      export:
        otlp:
          endpoint: ${TRACING_EXPORT_ENDPOINT:http://localhost:4318/v1/traces}
  otlp:
    metrics:
      export:
        url: ${METRICS_EXPORT_ENDPOINT:http://localhost:4318/v1/metrics}
